### ISSUE TITLE
Change `/ptr phase X` to petrify offenders

### ISSUE THREAD

**Issue by mako-taco** [mako-taco/EoTAddons#2]
When `/ptr phase X` is enabled, then spell casts for ranks which aren't in phase X should cause the caster to be afflicted by Petrification (`.nameaura 17624 playername`), and give them a whisper to explain what happened.

**Comment by colinsoleim** [comment]
I spent the morning looking into this, but I couldn't find a good way to implement it. After browsing the list of 1.12 events, it doesn't look like any of them return the spell rank/spell ID. I tried using DPSmate as a reference, but they use the CHAT_MSG_{specific_event} to log damage/healing, and those only return the chat message, e.g. "Your healing wave healed you for...", so impossible to tell what rank is being used.

@mako-taco Do you know of an event that gives the spell ID that I overlooked? Or can you think of another way of implementing this feature that I could try?

**Comment by mako-taco** [comment]
Ah, damn. Too bad. If we don't have ranks this wont work!
