### ISSUE TITLE
Add command /ptr roster

### ISSUE THREAD

**Issue by mako-taco** [mako-taco/EoTAddons#3]
We need the ability to copy the entire roster of the current raid for pasting into gdocs easily.
This helps us quickly ensure the assignment sheets are identical to our current raid groups.

The easiest way I have seen other addons do this is through a large, multi-line EditBox.  You populate the edit box, and the user copy/pastes. You can use `EOT_ForEachGroupMember` for iterating over the raid group (https://github.com/mako-taco/EoTAddons/blob/master/EoTUtils/ForEachGroupMember.lua).

The format of the edit box should be newline-separated names of players, e.g.
```
Lne
Xvk
Tipsi
Donvito
```

**Comment by colinsoleim** [comment]
I've submitted a PR for this here (https://github.com/mako-taco/EoTAddons/pull/4). Let me know what feedback you have.



Attached is a screenshot of what the editBox looks like for me locally.

![WoWScrnShot_080619_174018 (1)](https://user-images.githubusercontent.com/1221519/62582649-cd338900-b872-11e9-9fba-7db639cb0226.png)

**Comment by mako-taco** [comment]
closed by #4 (if you include 'fixes #3' in your commit message I believe github will automatically do this when it lands
